### ISSUE TITLE
As a user, I should be able to filter products by tag

### ISSUE THREAD

**Issue by luke-siedle** [gernzy/gernzy-server#35]
As a user, interacting with the graphql api, when running a query for products based on tag, I should be presented with a list of results (that I can paginate through).

This ticket involves a couple of things:
1) We need to use a relationship defined on the Product model, and a new model for Tag. 
2) We need to determine fields for the new Tag model and create the database migration for it. 
3) We need to consider whether a morphToMany relationship is required (i.e. will Tag be useful for other models or only the Product model). 
4) We need to make sure we can paginate the results (we may need a custom builder as per 
`GraphQL\\Builders\\ProductsBuilder@search` to allow us to filter the results correctly. 
5) We need to define exactly what we're expecting back in the products.graphql schema file. 

Process:
1) Start by writing a failing test which describes how you want to interact with graphql to get this information. 
2) As the test fails, keep adding your solutions.
3) Once the test has passed, think about other scenarios where a test is required, for example, what if no items are returned, is there a suitable message or does it fail? Write another test for this if necessary. (.e.g request a tag you know doesn't exist in another test, and see if it passes). 
4) Once all your tests are passing, think about how readable the code is and if it makes sense, and refactor where necessary. You can refactor safely and as long as your tests pass your code is still good. 

Notes:
The paginate directive has a specific structure to follow when querying:
https://lighthouse-php.com/3.7/api-reference/directives.html#paginate

Have a look at the test: 
https://github.com/gernzy/gernzy-server/blob/master/src/tests/Unit/viewProductsTest.php#L59
for reference on pagination.

**Comment by luke-siedle** [comment]
@AlexeiaW looks good for now, I'm approving this.

**Comment by AlexeiaW** [comment]
Ok awesome, thank you for the review
