### ISSUE TITLE
Update Lighthouse and Laravel to latest stable releases

### ISSUE THREAD

**Issue by luke-siedle** [gernzy/gernzy-server#56]
Would be great to get these up to date. We just need to address any test problems.

**Comment by AlexeiaW** [comment]
This test is failing with "You are not authorized to access order", and I am not too sure why

`public function testUserCanViewSingleOrderTheyCreated()`

**Comment by AlexeiaW** [comment]
This test is failing with "You are not authorized to access user", and I am not too sure why

`public function testNormalUserCanReadItself()`
