### ISSUE TITLE
As a user, my country location should be detected so I can browse and checkout faster because of prefilled values

### ISSUE THREAD

**Issue by luke-siedle** [gernzy/gernzy-server#59]
Woocommerce uses Maxmind https://maxmind.github.io/GeoIP2-php/ so we can follow them on this. 

Geolocation will be useful for the checkout process, as well as currrency detection, and even conditional showing of products (like regional restrictions which WooCommerce supports). 

For now we just need an endpoint in graphql allowing lazy detection of the user's location, without impacting on the initial session creation. I think we could build this into the initial createSession method but it may cause unwanted lag. 

We need to be able to store this in the session. We can use the arbitrary data storage in session for this. In SessionService this is `$sessionService->update(  [ "somekey" => "Somevalue" ] );`.

We would need a contract to allow other third party APIs to be used instead of Maxmind, though we will bind to Maxmind by default. 

Lastly, I guess we need an clear way to inject the user's location into our files. Maybe this is as simple as a method on the session service,`$sessionService->getCountryCode();` ?

**Comment by AlexeiaW** [comment]
Ok awesome, the use of a contract interface will be good to allow users to swap the implementation of the location provider.

Yeah a simple method on the sessionService to get the country code makes sense.
